### ISSUE TITLE
Is there a way to m

### ISSUE THREAD

**Issue by anthonyalvarez** [scronide/scuttle#12]
Hello,

Scuttle is great software. Been using it for a while now. But I have issues now.
# Questions
1. How to manage and delete users?
2. How to stop online registrations?
3. Does Scuttle have an administration page

Thank you.

**Comment by scronide** [comment]
1. There is no administration page. New users can sign up through the public registration form but, other than that, you have to manage users in the database.
2. The only way to do this to remove and unlink the register.php form.
3. Sadly not.
