### ISSUE TITLE
Error when uploading Delicious bookmarks file

### ISSUE THREAD

**Issue by anthonyalvarez** [scronide/scuttle#9]
Error message from /scuttle/import.php/ when importing a 600kb bookmarks file from Delicious 

> **XML error: not well-formed (invalid token) at line 39**

Love this project. It is a very useful piece of software. Any clues appreciated. 

Thank you.

**Comment by scronide** [comment]
Open up bookmark file and confirm that it's XML. If it's an HTML definition list, you'll need to use the importNetscape.php script instead.

If it is XML, try opening the bookmarks file directly in a browser (e.g. Chrome) to see if it reports any syntax errors. You can also check it for errors through the [W3C validator](http://validator.w3.org/).
